### ISSUE TITLE
update unsafe dependency com.puppycrawl.tools

### ISSUE THREAD

**Issue by RobertoC27** [ngeor/archetype-quickstart-jdk8#15]
Hello i was just testing a brand new repo with this archetype, after uploading it github's dependency checker raises and issue with the `com.puppycrawl.tools` dependency  stating that version should be at least 8.29. [8.10 is the one currently used] since the [repo](https://github.com/RobertoC27/maven-fat-jar) I tried it with its basic i could not check if the version bump will impact any stages. I'm fairly new to maven so I have no clue how to test it.
Roberto

**Comment by ngeor** [comment]
Hi @RobertoC27 , thanks for raising this. I made some changes and they will be published today under version 1.4.0. I think your issue has to do with the presence of the checkstyle plugin inside the `<reporting>` section. If you don't need it, just delete it from there completely ([lines 130-137 of your `pom.xml`](https://github.com/RobertoC27/maven-fat-jar/blob/master/pom.xml#L130-L137)).
